<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset=utf-8 />

	<title>Side2</title>

</head>

<body>

<p id="hello">Hello World</p>

<script type="text/javascript" charset="utf-8">
	txt = document.getElementById("hello").innerHTML;
//	document.getElementById("hello").innerHTML = "Test"
	document.write("<p>ID hello inneholder <q>" + txt + "</q>.</p>");
</script>

<script type="text/javascript" charset="utf-8">
	document.body.style.backgroundColor="yellow";
	document.body.style.color="blue";
</script>


<script type="text/javascript" charset="utf-8">
	document.write("<p>Simen was here...</p>");
</script>

<p>
	Her er det en paragraf til.
</p>
	
	
<!-- Dette er footeren til filen, og den skal typisk være nederst i html-filen. -->

<?php include "footer.html" ?>
	
</body>
</html>